### ISSUE TITLE
known-good dep versions

### ISSUE THREAD

**Issue by cbm755** [hanrach/p2d_fast_solver#9]
I'm going to track dependencies of what I need to get this running again.  This should be used to create a virtual env for reproducibility.  See also #7 

So far:

```
Ubuntu 20.04
Python 3.8
sudo apt install libsuitesparse-dev swig
pip install scikit-umfpack==0.3.2
pip install jax==0.2.20 jaxlib==0.1.71
```

- - - -

Newer Jax would probably require some effort.  I could not get old 0.2.20 jax to work on Python 3.10:
```
Traceback (most recent call last):
  File "/home/cbm/work/People/Rachel_Han/p2d_fast_solver.git/examples/main_reorder.py", line 1, in <module>
    from jax.config import config
    from jax._src.numpy import lax_numpy
  File "/home/cbm/.local/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 53, in <module>
    from jax._src.ops import scatter
  File "/home/cbm/.local/lib/python3.10/site-packages/jax/_src/ops/scatter.py", line 31, in <module>
    from typing import EllipsisType
ImportError: cannot import name 'EllipsisType' from 'typing' (/usr/lib64/python3.10/typing.py)
```

**Comment by jsfeng-fudan** [comment]
@cbm755  this error does not come from the Jax library but come from the Qrev() function. When I comment Qrev() function, the code can run smoothly. So I need help for computing heat generated by Qrev() function .
